import { MetadataRegistry } from '../../../compiler/registry';
import { HexaContext, ServiceMetadata } from '../../../compiler/di/types';
import { WorkerMetadata } from '../../../compiler/background/worker/types';
import { StoreScriptOutput } from '../../store/generator';
import { ConfigToken } from '../../../bin/config/config';
import { buildDependencyArgs, extractTokensForContext, generateTokenRegistrations, normalizeImportPath } from '../../shared';

export interface WorkerGeneratorOutput {
  hostRouterContent: string;
  workerScripts: { name: string; content: string }[];
  offscreenHtml: string | null;
}

export class WorkerGenerator {
  private registry: MetadataRegistry;
  private storeOutputs: StoreScriptOutput[];
  private tokens: ConfigToken[];
  private outputDir: string;
  private platform: string;

  constructor(registry: MetadataRegistry, storeOutputs: StoreScriptOutput[] = [], tokens: ConfigToken[] = [], outputDir: string = '', platform: string = 'chrome') {
    this.registry = registry;
    this.storeOutputs = storeOutputs;
    this.tokens = tokens;
    this.outputDir = outputDir;
    this.platform = platform;
  }

  public generate(): WorkerGeneratorOutput {
    const workers = this.registry.getWorkers();
    if (workers.length === 0) {
      return { hostRouterContent: '', workerScripts: [], offscreenHtml: null };
    }

    const workerScripts = workers.map(w => ({
      name: `worker-${w.name}`,
      content: this.generateWorkerScript(w),
    }));

    const hostRouterContent = this.generateHostRouter(workers);

    const hasDomWorker = workers.some(w => w.environment === 'dom');
    const isChromium = ['chrome', 'edge', 'brave', 'opera'].includes(this.platform);
    const offscreenHtml = hasDomWorker && isChromium ? this.generateOffscreenHtml() : null;

    return { hostRouterContent, workerScripts, offscreenHtml };
  }

  private generateWorkerScript(worker: WorkerMetadata): string {
    const services = this.getBackgroundServices();
    const relevantServices = this.getRelevantServices(worker, services);
    const backgroundTokens = extractTokensForContext(this.tokens, 'background');

    const imports = this.generateWorkerImports(worker, relevantServices);
    const containerSetup = this.generateWorkerContainerSetup(worker, relevantServices);
    const tokenRegistrations = generateTokenRegistrations(backgroundTokens);
    const methodsMap = this.generateMethodsMap(worker);

    return `/**
 * GENERATED BY HEXAJS - DO NOT EDIT
 * Worker Script: ${worker.name}
 */

${imports}

const container = new Container();
setContainer(container);

function setupDependencies() {
${containerSetup}
}

function registerTokens() {
${tokenRegistrations}
}

setupDependencies();
registerTokens();

const instance = new ${worker.className}(${buildDependencyArgs(worker)});

${methodsMap}
`;
  }

  private generateWorkerImports(worker: WorkerMetadata, services: ServiceMetadata[]): string {
    const imports: string[] = [
      `import { Container, setContainer, HEXA_PLATFORM } from '@hexajs/common';`,
      `import { RuntimePort } from '@hexajs/ports';`,
    ];

    services.forEach(service => {
      imports.push(`import { ${service.className} } from '${normalizeImportPath(service.importPath, this.outputDir)}';`);
    });

    imports.push(`import { ${worker.className} } from '${normalizeImportPath(worker.importPath, this.outputDir)}';`);

    return imports.join('\n');
  }

  private generateWorkerContainerSetup(worker: WorkerMetadata, services: ServiceMetadata[]): string {
    const registrations: string[] = [
      `  container.register(RuntimePort, (c) => new RuntimePort(c.resolve(HEXA_PLATFORM)));`,
    ];

    services.forEach(service => {
      const deps = buildDependencyArgs(service);
      registrations.push(`  container.register(${service.className}, (c) => new ${service.className}(${deps}));`);
    });

    return registrations.join('\n');
  }

  private generateMethodsMap(worker: WorkerMetadata): string {
    const entries = worker.publicMethods.map(m => `  ${m}: (...args) => instance.${m}(...args),`);

    return `export const methods = {
${entries.join('\n')}
};`;
  }

  private generateHostRouter(workers: WorkerMetadata[]): string {
    const mappingEntries = workers.map(w => `  '${w.name}': './worker-${w.name}.js',`);

    return `/**
 * GENERATED BY HEXAJS - DO NOT EDIT
 * Worker Host Router
 */

const WORKER_MAP = {
${mappingEntries.join('\n')}
};

const workerCache = new Map();

async function loadWorker(workerName) {
  if (workerCache.has(workerName)) {
    return workerCache.get(workerName);
  }

  const scriptPath = WORKER_MAP[workerName];
  if (!scriptPath) {
    throw new Error('[HexaJS] Unknown worker: ' + workerName);
  }

  const mod = await import(scriptPath);
  workerCache.set(workerName, mod.methods);
  return mod.methods;
}

async function handleWorkerCall(payload) {
  const { callId, workerName, method, args } = payload;

  const methods = await loadWorker(workerName);
  if (!methods[method]) {
    throw new Error('[HexaJS] Worker "' + workerName + '" has no method "' + method + '"');
  }

  const previousContext = globalThis.__HEXA_ACTIVE_WORKER_CALL__;
  globalThis.__HEXA_ACTIVE_WORKER_CALL__ = { callId, workerName };

  try {
    return await methods[method](...args);
  } finally {
    globalThis.__HEXA_ACTIVE_WORKER_CALL__ = previousContext;
  }
}

// Listen for HEXA_WORKER_CALL messages
if (typeof self !== 'undefined' && typeof self.onmessage !== 'undefined') {
  self.onmessage = async (event) => {
    const { type, callId, workerName, method, args } = event.data;
    if (type !== 'HEXA_WORKER_CALL') return;

    try {
      const result = await handleWorkerCall({ workerName, method, args });
      self.postMessage({ callId, success: true, data: result });
    } catch (err) {
      self.postMessage({ callId, success: false, error: err?.message ?? 'Worker execution failed' });
    }
  };
}

// Listen for runtime messages (offscreen/background relay)
if (typeof chrome !== 'undefined' && chrome.runtime?.onMessage) {
  chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
    if (message?.type !== 'HEXA_WORKER_CALL') return false;

    handleWorkerCall(message)
      .then(result => sendResponse({ callId: message.callId, success: true, data: result }))
      .catch(err => sendResponse({ callId: message.callId, success: false, error: err?.message ?? 'Worker execution failed' }));

    return true;
  });
}
`;
  }

  private generateOffscreenHtml(): string {
    return `<!DOCTYPE html>
<html>
<head>
  <script src="hexa.worker.js" type="module"></script>
</head>
<body></body>
</html>
`;
  }

  private getBackgroundServices(): ServiceMetadata[] {
    return this.registry.getServices().filter(s => s.context === HexaContext.Background || s.context === HexaContext.General);
  }

  private getRelevantServices(worker: WorkerMetadata, allServices: ServiceMetadata[]): ServiceMetadata[] {
    const needed = new Set<string>();
    const serviceMap = new Map(allServices.map(s => [s.className, s]));

    const collect = (deps: string[]) => {
      for (const dep of deps) {
        if (needed.has(dep)) continue;
        const service = serviceMap.get(dep);
        if (service) {
          needed.add(dep);
          collect(service.dependencies);
        }
      }
    };

    collect(worker.dependencies);
    return allServices.filter(s => needed.has(s.className));
  }

}
