import { MetadataRegistry } from '../../compiler/registry';

interface ValidationModuleOutput {
    background: string;
    content: string;
}

interface RouteValidationEntry {
    route: string;
    dtoType: string;
}

export class ValidatorGenerator {
    constructor(private registry: MetadataRegistry) { }

    public generate(): ValidationModuleOutput {
        return {
            background: this.generateContextModule(this.getBackgroundInboundRoutes(), this.getBackgroundOutboundRoutes()),
            content: this.generateContextModule(this.getContentInboundRoutes(), this.getContentOutboundRoutes())
        };
    }

    private getBackgroundInboundRoutes(): RouteValidationEntry[] {
        return this.registry.getControllers()
            .flatMap(controller => controller.methods
                .filter(method => !!method.actionName && !!method.payloadDtoType)
                .map(method => ({ route: method.actionName!, dtoType: method.payloadDtoType! })));
    }

    private getBackgroundOutboundRoutes(): RouteValidationEntry[] {
        return this.registry.getControllers()
            .flatMap(controller => controller.methods
                .filter(method => !!method.actionName && !!method.responseDtoType)
                .map(method => ({ route: method.actionName!, dtoType: method.responseDtoType! })));
    }

    private getContentInboundRoutes(): RouteValidationEntry[] {
        return this.registry.getHandlers()
            .flatMap(handler => handler.methods
                .filter(method => !!method.handleName && !!method.payloadDtoType)
                .map(method => ({ route: method.handleName!, dtoType: method.payloadDtoType! })));
    }

    private getContentOutboundRoutes(): RouteValidationEntry[] {
        return this.registry.getHandlers()
            .flatMap(handler => handler.methods
                .filter(method => !!method.handleName && !!method.responseDtoType)
                .map(method => ({ route: method.handleName!, dtoType: method.responseDtoType! })));
    }

    private generateContextModule(inboundRoutes: RouteValidationEntry[], outboundRoutes: RouteValidationEntry[]): string {
        const usedDtos = [...new Set([...inboundRoutes, ...outboundRoutes].map(route => route.dtoType))]
            .map(dtoType => this.registry.getDtoValidation(dtoType))
            .filter((dto): dto is NonNullable<typeof dto> => !!dto);

        const inboundValidators = usedDtos.map(dto => this.generateInboundDtoValidator(dto.className, dto.properties));
        const outboundValidators = usedDtos.map(dto => this.generateOutboundDtoValidator(dto.className, dto.properties, dto.hasIndexSignature));
        const inboundRouteLines = inboundRoutes
            .filter(route => usedDtos.some(dto => dto.className === route.dtoType))
            .map(route => `  '${route.route}': validate${route.dtoType},`)
            .join('\n');
        const outboundRouteLines = outboundRoutes
            .filter(route => usedDtos.some(dto => dto.className === route.dtoType))
            .map(route => `  '${route.route}': validateResponse${route.dtoType},`)
            .join('\n');

        return `/** 
 * GENERATED BY HEXAJS - DO NOT EDIT 
 * AOT Validation Registry
 */

${inboundValidators.join('\n\n')}

${outboundValidators.join('\n\n')}

const routeValidators = {
${inboundRouteLines}
};

const routeResponseValidators = {
${outboundRouteLines}
};

export function createAotValidationPipe() {
  return (input) => {
    const validator = routeValidators[input.route];
    if (!validator) {
      return input.payload;
    }

    const result = validator(input.payload);
    if (!result.valid) {
      return {
        valid: false,
        error: result.error,
        code: 'HEXA_VALIDATION_FAILED',
        details: result.details
      };
    }

    return input.payload;
  };
}

export function createAotOutboundValidationPipe() {
    return (input) => {
        const validator = routeResponseValidators[input.route];
        if (!validator) {
            return input.payload;
        }

        const result = validator(input.payload);
        if (!result.valid) {
            return {
                valid: false,
                error: result.error,
                code: 'HEXA_RESPONSE_VALIDATION_FAILED',
                details: result.details
            };
        }

        return input.payload;
    };
}
`;
    }

        private generateInboundDtoValidator(className: string, properties: Array<{ name: string; decorators: Array<{ name: string; args: unknown[] }> }>): string {
        const checks: string[] = [
            `  if (!data || typeof data !== 'object') return { valid: false, error: '${className} payload must be an object' };`
        ];

        properties.forEach(property => {
            const accessor = `data.${property.name}`;
            const decorators = property.decorators.map(d => d.name);
            const hasOptional = decorators.includes('IsOptional');

            if (hasOptional) {
                checks.push(`  if (${accessor} === undefined || ${accessor} === null) {`);
                checks.push(`    // optional field, skip validations`);
                checks.push(`  } else {`);
                this.appendDecoratorChecks(checks, accessor, property.name, property.decorators, '    ');
                checks.push(`  }`);
                return;
            }

            this.appendDecoratorChecks(checks, accessor, property.name, property.decorators, '  ');
        });

        checks.push(`  return { valid: true };`);

        return `function validate${className}(data) {\n${checks.join('\n')}\n}`;
    }

    private generateOutboundDtoValidator(className: string, properties: Array<{ name: string; decorators: Array<{ name: string; args: unknown[] }> }>, hasIndexSignature: boolean): string {
        const checks: string[] = [
            `  if (!data || typeof data !== 'object') return { valid: false, error: '${className} response must be an object' };`
        ];

        properties.forEach(property => {
            const accessor = `data.${property.name}`;
            const decorators = property.decorators.map(d => d.name);
            const hasOptional = decorators.includes('IsOptional');

            if (hasOptional) {
                checks.push(`  if (${accessor} === undefined || ${accessor} === null) {`);
                checks.push(`    // optional field, skip validations`);
                checks.push(`  } else {`);
                this.appendDecoratorChecks(checks, accessor, property.name, property.decorators, '    ');
                checks.push(`  }`);
                return;
            }

            this.appendDecoratorChecks(checks, accessor, property.name, property.decorators, '  ');
        });

        if (!hasIndexSignature) {
            const allowedKeys = properties.map(property => property.name);
            checks.push(`  const allowedKeys = new Set(${JSON.stringify(allowedKeys)});`);
            checks.push(`  const extraKeys = Object.keys(data).filter(key => !allowedKeys.has(key));`);
            checks.push(`  if (extraKeys.length > 0) return { valid: false, error: '${className} response has unknown properties', details: { extraKeys } };`);
        }

        checks.push(`  return { valid: true };`);

        return `function validateResponse${className}(data) {\n${checks.join('\n')}\n}`;
    }

    private appendDecoratorChecks(target: string[], accessor: string, propertyName: string, decorators: Array<{ name: string; args: unknown[] }>, indent: string): void {
        decorators.forEach(decorator => {
            switch (decorator.name) {
                case 'IsDefined':
                    target.push(`${indent}if (${accessor} === undefined) return { valid: false, error: '${propertyName} is required' };`);
                    break;
                case 'IsNotEmpty':
                    target.push(`${indent}if (${accessor} === '' || ${accessor} === null || ${accessor} === undefined) return { valid: false, error: '${propertyName} should not be empty' };`);
                    break;
                case 'IsString':
                    target.push(`${indent}if (typeof ${accessor} !== 'string') return { valid: false, error: '${propertyName} must be a string' };`);
                    break;
                case 'IsBoolean':
                    target.push(`${indent}if (typeof ${accessor} !== 'boolean') return { valid: false, error: '${propertyName} must be a boolean' };`);
                    break;
                case 'IsNumber':
                    target.push(`${indent}if (typeof ${accessor} !== 'number' || Number.isNaN(${accessor})) return { valid: false, error: '${propertyName} must be a number' };`);
                    break;
                case 'IsInt':
                    target.push(`${indent}if (!Number.isInteger(${accessor})) return { valid: false, error: '${propertyName} must be an integer' };`);
                    break;
                case 'IsArray':
                    target.push(`${indent}if (!Array.isArray(${accessor})) return { valid: false, error: '${propertyName} must be an array' };`);
                    break;
                case 'Min':
                    target.push(`${indent}if (typeof ${accessor} !== 'number' || ${accessor} < ${Number(decorator.args[0])}) return { valid: false, error: '${propertyName} must be >= ${Number(decorator.args[0])}' };`);
                    break;
                case 'Max':
                    target.push(`${indent}if (typeof ${accessor} !== 'number' || ${accessor} > ${Number(decorator.args[0])}) return { valid: false, error: '${propertyName} must be <= ${Number(decorator.args[0])}' };`);
                    break;
                case 'MinLength':
                    target.push(`${indent}if (typeof ${accessor} !== 'string' || ${accessor}.length < ${Number(decorator.args[0])}) return { valid: false, error: '${propertyName} length must be >= ${Number(decorator.args[0])}' };`);
                    break;
                case 'MaxLength':
                    target.push(`${indent}if (typeof ${accessor} !== 'string' || ${accessor}.length > ${Number(decorator.args[0])}) return { valid: false, error: '${propertyName} length must be <= ${Number(decorator.args[0])}' };`);
                    break;
                case 'Length': {
                    const min = Number(decorator.args[0]);
                    const max = Number(decorator.args[1]);
                    target.push(`${indent}if (typeof ${accessor} !== 'string' || ${accessor}.length < ${min} || ${accessor}.length > ${max}) return { valid: false, error: '${propertyName} length must be between ${min} and ${max}' };`);
                    break;
                }
                case 'Matches': {
                    const pattern = typeof decorator.args[0] === 'string' ? decorator.args[0] : '';
                    target.push(`${indent}if (typeof ${accessor} !== 'string' || !new RegExp(${JSON.stringify(pattern)}).test(${accessor})) return { valid: false, error: '${propertyName} has invalid format' };`);
                    break;
                }
                case 'IsEmail':
                    target.push(`${indent}if (typeof ${accessor} !== 'string' || !/^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(${accessor})) return { valid: false, error: '${propertyName} must be a valid email' };`);
                    break;
                default:
                    break;
            }
        });
    }
}
