import * as path from 'path';
import type { Plugin } from 'vite';

const BOOTSTRAP_ALIAS = '@hexa/bootstrap';

export interface HexaBootstrapPluginOptions {
  watch?: boolean;
  hmrAddress?: string;
  hmrSessionToken?: string;
  surface?: 'popup' | 'devtools' | 'newtab';
}

const MAX_HMR_ADDRESS_LENGTH = 2048;
const HMR_TOKEN_PATTERN = /^[a-zA-Z0-9._-]{16,128}$/;

function normalizeHmrAddress(value: string): string {
  const trimmed = value.trim();
  if (!trimmed) {
    return '';
  }

  if (trimmed.length > MAX_HMR_ADDRESS_LENGTH) {
    throw new Error(`[Hexa UI] hmrAddress is too long (max ${MAX_HMR_ADDRESS_LENGTH} chars).`);
  }

  let parsed: URL;
  try {
    parsed = new URL(trimmed);
  } catch {
    throw new Error('[Hexa UI] hmrAddress must be a valid ws:// or wss:// URL.');
  }

  if (parsed.protocol !== 'ws:' && parsed.protocol !== 'wss:') {
    throw new Error('[Hexa UI] hmrAddress must use ws:// or wss:// protocol.');
  }

  return parsed.toString();
}

function normalizeHmrToken(value: string): string {
  const trimmed = value.trim();
  if (!trimmed) {
    return '';
  }

  if (!HMR_TOKEN_PATTERN.test(trimmed)) {
    throw new Error('[Hexa UI] hmrSessionToken must be 16-128 chars and match [a-zA-Z0-9._-].');
  }

  return trimmed;
}

function createHMRRuntime(hmrAddress: string, hmrSessionToken: string, surface?: string): string {
  const surfaceJson = surface ? JSON.stringify(surface) : 'undefined';
  return `
const __HEXA_HMR_URL__ = ${JSON.stringify(hmrAddress)};
const __HEXA_HMR_SESSION_TOKEN__ = ${JSON.stringify(hmrSessionToken)};
const __HEXA_HMR_SURFACE__ = ${surfaceJson};
(() => {
  if (typeof window === 'undefined' || !__HEXA_HMR_URL__ || !__HEXA_HMR_SESSION_TOKEN__) {
    return;
  }

  function hexaHmrReload() {
    // Cache-busting navigation forces the browser to bypass extension resource caching
    // (required for devtools panels where plain reload() may serve stale assets).
    const base = window.location.pathname;
    window.location.href = base + '?hexa-hmr=' + Date.now();
  }

  const ws = new WebSocket(__HEXA_HMR_URL__);
  ws.addEventListener('open', () => {
    ws.send(JSON.stringify({ type: 'auth', token: __HEXA_HMR_SESSION_TOKEN__, timestamp: Date.now() }));
  });
  ws.addEventListener('message', (event) => {
    let payload;
    try {
      payload = JSON.parse(event.data);
    } catch {
      return;
    }

    if (!payload || typeof payload !== 'object' || typeof payload.type !== 'string') {
      return;
    }

    // If a surface is set, only react to events targeting this surface
    if (__HEXA_HMR_SURFACE__ && payload.surface && payload.surface !== __HEXA_HMR_SURFACE__) {
      return;
    }

    if (payload.type === 'ui:reload') {
      hexaHmrReload();
      return;
    }

    if (payload.type === 'ui:update') {
      const now = Date.now();
      const changedPath = typeof payload.changedPath === 'string' ? payload.changedPath : '';
      if (changedPath.endsWith('.css') || changedPath.endsWith('.scss')) {
        const links = document.querySelectorAll('link[rel="stylesheet"]');
        links.forEach((link) => {
          const href = link.getAttribute('href');
          if (!href) {
            return;
          }
          const url = new URL(href, window.location.href);
          url.searchParams.set('hexa-hmr', String(now));
          link.setAttribute('href', url.toString());
        });
        return;
      }

      hexaHmrReload();

    }
  });
})();
`;
}

/**
 * Vite plugin that resolves the `@hexa/bootstrap` alias to the pre-built
 * `ui.bootstrap.js` file in the output directory, and auto-injects the
 * import into entry files so users never need to reference it manually.
 *
 * The bootstrap file is a side-effect-only module generated by the CLI
 * (`hexa build`). It creates the DI container, wires all UI/General
 * services and tokens, and calls `setContainer()` from `@hexajs-dev/common`.
 * After that, `import { inject } from '@hexajs-dev/common'` works everywhere.
 *
 * @param bootstrapPath Absolute path to the generated `ui.bootstrap.js` file.
 */
export function hexaBootstrapPlugin(bootstrapPath: string, options: HexaBootstrapPluginOptions = {}): Plugin {
  const normalizedBootstrap = bootstrapPath.replace(/\\/g, '/');
  const normalizedHmrAddress = options.hmrAddress ? normalizeHmrAddress(options.hmrAddress) : '';
  const normalizedHmrToken = options.hmrSessionToken ? normalizeHmrToken(options.hmrSessionToken) : '';
  const injectHMR = !!options.watch && !!normalizedHmrAddress && !!normalizedHmrToken;
  const hmrRuntime = injectHMR ? createHMRRuntime(normalizedHmrAddress, normalizedHmrToken, options.surface) : '';

  return {
    name: 'hexa-bootstrap-inject',
    enforce: 'pre',

    config() {
      return {
        resolve: {
          alias: {
            [BOOTSTRAP_ALIAS]: normalizedBootstrap,
          },
        },
      };
    },

    transform(code, id) {
      const normalizedId = id.replace(/\\/g, '/');
      if (normalizedId === normalizedBootstrap) return null;
      if (!/\.(tsx?|jsx?)$/.test(normalizedId)) return null;

      // Inject bootstrap import into panel entries (main.tsx/ts) and bridge (devtools.ts).
      // HMR runtime is only injected into panel entries — the bridge creates panels
      // and does not render UI, so it does not need hot-reload.
      const basename = path.basename(normalizedId);
      if (basename.startsWith('main.') || basename === 'devtools.ts') {
        const hmrBlock = injectHMR && basename.startsWith('main.') ? `${hmrRuntime}\n` : '';
        return `${hmrBlock}import '${BOOTSTRAP_ALIAS}';\n${code}`;
      }
      return null;
    },
  };
}
