import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      customProps: { icon: 'rocket' },
      link: { type: 'doc', id: 'getting-started/index' },
      items: [
        'getting-started/installation',
        'getting-started/first-steps',
      ],
    },
    {
      type: 'category',
      label: 'Build Your First Extension',
      collapsed: false,
      customProps: { icon: 'hammer' },
      link: { type: 'doc', id: 'build-your-first-extension/index' },
      items: [
        'build-your-first-extension/create-grayscale-extension',
        'build-your-first-extension/popup-preview',
        'build-your-first-extension/running-and-debugging',
      ],
    },
    {
      type: 'category',
      label: 'Core Fundamentals',
      collapsed: false,
      customProps: { icon: 'puzzle' },
      link: { type: 'doc', id: 'core-fundamentals/index' },
      items: [
        'core-fundamentals/architecture',
        'core-fundamentals/dependency-injection',
        'core-fundamentals/controllers',
        'core-fundamentals/handlers',
        'core-fundamentals/tokens',
        'core-fundamentals/message-routing',
        'core-fundamentals/validation-pipes',
        'core-fundamentals/workers',
      ],
    },
    {
      type: 'category',
      label: 'State Management',
      collapsed: false,
      customProps: { icon: 'database' },
      link: { type: 'doc', id: 'state-management/index' },
      items: [
        'state-management/store',
        'state-management/actions',
        'state-management/reducers',
        'state-management/effects',
        'state-management/rxjs',
      ],
    },
    {
      type: 'category',
      label: 'Managed UI',
      collapsed: false,
      customProps: { icon: 'paintbrush' },
      link: { type: 'doc', id: 'managed-ui/index' },
      items: [
        'managed-ui/popup',
        'managed-ui/devtools',
        'managed-ui/react-integration',
        'managed-ui/shadow-views',
      ],
    },
    {
      type: 'category',
      label: 'Browser-Agnostic',
      collapsed: false,
      customProps: { icon: 'shuffle' },
      link: { type: 'doc', id: 'browser-agnostic-messaging/index' },
      items: [
        'browser-agnostic-messaging/hexa-bridge',
        'browser-agnostic-messaging/custom-port',
      ],
    },
    {
      type: 'category',
      label: 'CLI & Tooling',
      collapsed: false,
      customProps: { icon: 'cog' },
      link: { type: 'doc', id: 'cli-tooling/index' },
      items: [
        'cli-tooling/cli-commands',
        'cli-tooling/build-pipeline',
        'cli-tooling/manifest-patching',
        'cli-tooling/hmr',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      collapsed: true,
      customProps: { icon: 'book' },
      link: { type: 'doc', id: 'api-reference/index' },
      items: [
        {
          type: 'category',
          label: 'General Ports',
          link: { type: 'doc', id: 'api-reference/general/index' },
          items: [
            'api-reference/general/runtime-port',
            'api-reference/general/i18n-port',
            'api-reference/general/extension-port',
          ],
        },
        {
          type: 'category',
          label: 'Background Ports',
          link: { type: 'doc', id: 'api-reference/background/index' },
          items: [
            'api-reference/background/action-port',
            'api-reference/background/alarms-port',
            'api-reference/background/bookmarks-port',
            'api-reference/background/browser-action-port',
            'api-reference/background/browsing-data-port',
            'api-reference/background/commands-port',
            'api-reference/background/cookies-port',
            'api-reference/background/declarative-net-request-port',
            'api-reference/background/downloads-port',
            'api-reference/background/history-port',
            'api-reference/background/identity-port',
            'api-reference/background/idle-port',
            'api-reference/background/management-port',
            'api-reference/background/menus-port',
            'api-reference/background/notifications-port',
            'api-reference/background/page-action-port',
            'api-reference/background/permissions-port',
            'api-reference/background/scripting-port',
            'api-reference/background/storage-port',
            'api-reference/background/tab-groups-port',
            'api-reference/background/tabs-port',
            'api-reference/background/user-scripts-port',
            'api-reference/background/web-navigation-port',
            'api-reference/background/web-request-port',
          ],
        },
        {
          type: 'category',
          label: 'UI Ports',
          link: { type: 'doc', id: 'api-reference/ui/index' },
          items: [
            'api-reference/ui/devtools-port',
          ],
        },
        {
          type: 'category',
          label: 'Content Ports',
          link: { type: 'doc', id: 'api-reference/content/index' },
          items: [],
        },
      ],
    },
  ],
};

export default sidebars;
